name: Pull request check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install dependencies
        run: yarn

      - name: Create fake config file
        run: |
          echo "{\"PORT\": \"0000\", \"API\": \"http://localhost:0001\"}" > ./src/config.json

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: CI=false yarn maso:build